### PR TITLE
Support python-pqueue on Windows

### PR DESCRIPTION
**Pull request by peter-wangxu**
On Windows, os.rename cannot overwrite the existing files, this causes
WindowsError. We need to remove the info file before rename with tempinfo.

### CODE REVIEW

**Comment by peter-wangxu** [comment]
@balena Please help to review and verify this if no issue.

**Comment by balena** [comment]
Dear Mr. Wang,

Unfortunately the solution you are proposing is wrong, because of the lack of "atomicity" of the operation involved. Say your program crashes in the exact moment you removed the 'info' file, before renaming the new one: you will end up losing everything. You may argue that at this moment we may attempt to reconstruct the index, but this always involves other kinds of problems like initialization time, and "reincarnation" of already processed data. Simplicity is key.

You should find an operation in Windows equivalent to the POSIX "os.rename". The whole new 'info' file has to be substituted atomically: it means all or nothing at all is written (you end up having the old file or the new file, never other condition).

Regards,
G. B. Versiani.

**Comment by balena** [comment]
The link http://stupidpythonideas.blogspot.com.br/2014/07/getting-atomic-writes-right.html is a good start. Note the following excerpt: "(...) you should use the Win32 API function ReplaceFile that does it for you. You can call this via PyWin32, or via ctypes, basically as shown above for MoveFileEx."

**Comment by peter-wangxu** [comment]
I understood the situation of "atomicity", but I do not want to introduce the "PyWin32" which has OS dependency. do you have any other suggestion?

And i found other issue on Windows: 

```
AssertionError: Empty not raised
```

is it related to this?

**Pull request closed without merging**
