### PR TITLE
fix: get removes old queue file even without calling task_done().

### PR DESCRIPTION
**Pull request by gfreezy**

### CODE REVIEW

**Comment by peter-wangxu** [comment]
@gfreezy As far as I understood, the original behavior would cause failure when reading from a deleted tail file, can you confirm?

I would like to port this fix to [persist-queue](https://github.com/peter-wangxu/persist-queue).
Thanks
Peter

**Comment by balena** [comment]
@gfreezy, thanks a lot. Sorry for the long time to merge, I have been too busy since December.

**Comment by balena** [comment]
@peter-wangxu, looks like you created another package with about the same functionality, with just a few changes to make it work on Windows, which is definitely not recommended as none of the file operations are really atomic (you may be fooling the developer, as there may be data lose), and you also added a timer to the (already) atomic operation `Queue.put`. Sorry the French, but you created a Frankenstein! :)

**Comment by peter-wangxu** [comment]
@balena, not just some workaround for windows, I fully tested python-pqueue on greenlet/eventlet environment, and found some issue( probably implementation flaw in them). So I decided to start a new project for my use. Actually, the timer was added for green compatibility.

For the windows issue, I will change my wording in the readme to notice possible users.
I also plan to add atomic operation support for windows later.

**Comment by balena** [comment]
@peter-wangxu, these are the differences:
* You do not comply with [python Queue](https://docs.python.org/2/library/queue.html) anymore, you inherit directly from `object`, not from the base `Queue` class, so you copied some methods from there -- if Python decides to enhance it somehow (improve internally) you will have to detect and copy the methods again;
* The user can implement itself ways to deal with a max number of elements, and wait if he needs; this new feature is adding more than needed for a great parcel of users;
* It would be great if you tell me what error you get on greenlet/eventlet when using the `Queue` object, I will be certainly eager to find a solution if this is all about.
* Finally, you modified the code LICENSE from BSD to Apache 2.0. It states clearly:

    3. Neither the name of python-pqueue nor the names of its contributors may be used
       to endorse or promote products derived from this software without
       specific prior written permission.

So, if you decide to continue with your library, I request you to remove all references to the `python-pqueue` implementation.

**Comment by balena** [comment]
@peter-wangxu, Ah, and you states apparently in a wrong way that only persist-queue can serialize objects through `pickle`, while you just copied from the original implementation!

**Comment by peter-wangxu** [comment]
@balena I noticed that you changed your license wording.
For the time being, I will change the license to the copy of YOURS!,
Sorry for confusions (by my readme and license) if you felt offense:), I will modify them.

Let me know if you still have concern.

**Comment by peter-wangxu** [comment]
@balena https://github.com/peter-wangxu/persist-queue/pull/10 patch to change license to BSD.
Please review it.

**Comment by balena** [comment]
@peter-wangxu, all I did was to change the reference to "Scrapy" which is obviously wrong (copy-and-paste error) to python-pqueue. But the license was always BSD-3-clause since day one. You are not obliged to adopt the BSD license in your derived work; but if you change the license, you should not do any reference to python-pequeue in your README file anymore.

If you opt by the BSD license, you should add your name below mine, indicating you have done some extra work after me.

**Comment by peter-wangxu** [comment]
@balena Got you, will add my name in license. keeping bsd is fine for me.

**Pull request merged**
